---
title: "Palmenr Penguins dataset"
subtitle: 'MSc in Statistics 2025/26, Imperial College London'
author: "Tarun Rajan"
format:
  html:
    toc: true
    highlight: tango
    self-contained: true
    df-print: paged
  pdf: default
format-links: false
bibliography: "MSc_Statistics_coursework_template_quarto.bib" 
---

<style type="text/css">
h1{
  font-size: 24pt;
}
h2{
  font-size: 18pt;
}
body{
  font-size: 12pt;
}
</style>

```{r setup, include = FALSE, tidy=TRUE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
include_solutions <- TRUE
```
```{r setup2, include=FALSE, tidy=TRUE}
require(rmarkdown)
require(knitr)
require(kableExtra)
# Put any library imports and other preamble here.
```



```{r, echo = FALSE, message=FALSE}
# Load library
library(palmerpenguins)

# Load penguins dataset
data('penguins')
```


```{r,echo = FALSE}
true_false <- apply(is.na(penguins), 1, any)

penguins$missing_values <- c(true_false)

df <- table(penguins$species)

```

```{r, echo = FALSE}
#| label: tbl-palmer
#| tbl-cap: "Species count for penguins."

kbl(df,
    caption = 'Spcies count', 
    label = 'species_count',
    digits = 2) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed"),
    font_size = 12)

```
@tbl-palmer provides the count for each species of penguin.

Here is some information on Adélie Penguin @wikipedia2025adeliepenguin

```{r,echo = FALSE}

species_names <- as.character((unique(penguins$species)))


for (species in species_names){
  bill_lengths <- penguins$bill_length_mm[penguins$species == species]
  cat(species,"has mean bill length of",(mean(bill_lengths,na.rm = TRUE)),"\n")
}

for (species in species_names){
  flipper_lengths <- penguins$flipper_length_mm[penguins$species == species]
  cat(species,"has mean flipper length of",(mean(flipper_lengths,na.rm = TRUE)),"\n")
}

# Question 4
species_mean <- function(variable){
  results <- c()
  for (species in species_names){
  values <- penguins[[variable]][penguins$species == species]
  msg <- paste(species,"has mean",variable,"of",(mean(values,na.rm = TRUE)))
  results <- c(results, msg)
  }
  return(results)
}

species_mean("flipper_length_mm")
```

```{r}
#| label: fig-scatter
#| tbl-cap: "Scatter plot of two simulated datasets."
#| 
# Question 5
x = penguins$flipper_length_mm
y = penguins$body_mass_g

plot(x,y)
```
@fig-scatter shows a scatter plot of body mass vs flipper length.


# Code appendix

```{r ref.label=knitr::all_labels(), echo = T, eval = F}
```

# References


::: {#refs}
:::

